apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-example-workshop-3"
spec:
  title: "Java Workshop #3"
  description: "Install Java extensions from local web server."
  publish:
    image: $(image_repository)/labs-java-dev-testing/lab-example-workshop-3:$(workshop_version)
  workshop:
    image: jdk17-environment:*
    files:
    - image:
        url: $(image_repository)/labs-java-dev-testing/lab-example-workshop-3:$(workshop_version)
      includePaths:
      - /workshops/lab-example-workshop-3/workshop/**
      - /workshops/lab-example-workshop-3/exercises/**
      - /workshops/lab-example-workshop-3/README.md
      newRootPath: workshops/lab-example-workshop-3
    - path: .local/share/code-server/extensions
      http:
        url: "http://$(assets_repository)/extensions.tar.gz"
  environment:
    assets:
      storage: 5Gi
      ingress:
        enabled: true
      files: 
      - image:
          url: ghcr.io/grahamdumpleton/vscode-java-extensions-tar:latest
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: assets
      host: $(assets_repository)
